name: 'Shell Linter'
description: 'Execute lint check on shell scripts using ShellCheck'
author: 'ep-mobile'
inputs:
  path:
    description: 'Execute lint check on a specific file or folder.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
branding:
  icon: 'check-circle'
  color: 'yellow'