name: CI Pipeline

on: 
  pull_request:
  push:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Shellcheck
        run: ./src/install_shellcheck.sh
      - name: Run tests
        run: ./tests/test_runner
        shell: bash
    

